spring.application.name=servicejc

# OJO: Para pruebas locales está bien, pero en Google Cloud esto fallará 
# si no le pasas el archivo JSON de otra forma (o usas las credenciales por defecto de GCP).
FIREBASE_CREDENTIALS=C:/Users/User/Documents/GitHub/ServiceJC/servicejc-backend/serviceAccountKey.json

firebase.storage.bucket-name=servicejc-d3aca.appspot.com

# La URL de Cubo
cubo.api.url=https://api-payment-sandbox.cubopago.com/api/v1/transactions

# 👉 LA SINTAXIS CORRECTA PARA LA API KEY:
cubo.api.key=${CUBO_API_KEY:898b22537004222148a060e2ae47338f892aa07880423ca085942adca1e96c6663b526728c3c9f8fe0dc692c6aea8bdd}